
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EZIO
 */
public class Play extends javax.swing.JFrame {

    
    public static String p1name,p2name;
    
    int i=1;
    String j="joker";
    
    public Play() {
        initComponents();
        jTextField1.setEditable(false);
        P1Name.setVisible(false);
        P2Name.setVisible(false);
        P2Name.enable(false);
        P1Name.enable(false);
        PvP.setOpaque(false);
        PvP.setContentAreaFilled(false);
        PvP.setBorderPainted(true);
        
        PvC.setOpaque(false);
        PvC.setContentAreaFilled(false);
        PvC.setBorderPainted(true);
        
        
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(true);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PvC = new javax.swing.JButton();
        PvP = new javax.swing.JButton();
        P1Name = new javax.swing.JTextField();
        P2Name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        PvC.setBackground(new java.awt.Color(153, 255, 153));
        PvC.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        PvC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PC.gif"))); // NOI18N
        PvC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PvCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PvCMouseExited(evt);
            }
        });
        PvC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PvCActionPerformed(evt);
            }
        });
        getContentPane().add(PvC);
        PvC.setBounds(300, 30, 320, 280);

        PvP.setBackground(new java.awt.Color(153, 255, 153));
        PvP.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        PvP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/P.png"))); // NOI18N
        PvP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PvPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PvPMouseExited(evt);
            }
        });
        PvP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PvPActionPerformed(evt);
            }
        });
        getContentPane().add(PvP);
        PvP.setBounds(790, 10, 220, 280);

        P1Name.setBackground(new java.awt.Color(0, 153, 153));
        P1Name.setForeground(new java.awt.Color(204, 204, 204));
        P1Name.setText("Enter Your Name");
        P1Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P1NameMouseClicked(evt);
            }
        });
        P1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1NameActionPerformed(evt);
            }
        });
        getContentPane().add(P1Name);
        P1Name.setBounds(380, 410, 240, 40);

        P2Name.setBackground(new java.awt.Color(0, 153, 153));
        P2Name.setForeground(new java.awt.Color(204, 204, 204));
        P2Name.setText("Enter Your Name");
        P2Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P2NameMouseClicked(evt);
            }
        });
        P2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2NameActionPerformed(evt);
            }
        });
        getContentPane().add(P2Name);
        P2Name.setBounds(830, 410, 240, 40);

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1150, 650, 110, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pVSpc.png"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel2MouseWheelMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 290, 213, 113);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pVSp.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(213, 113));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(880, 290, 213, 113);

        jTextField1.setBackground(new java.awt.Color(255, 255, 0));
        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 153));
        jTextField1.setText("Select Your Avatar");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 610, 180, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/point.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 590, 138, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/joker.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 420, 200, 320);

        next.setBackground(new java.awt.Color(0, 0, 0));
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/next3.png"))); // NOI18N
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(883, 590, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PvPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PvPActionPerformed
        // TODO add your handling code here:
        P1Name.setVisible(true);
        P2Name.setVisible(true);
    }//GEN-LAST:event_PvPActionPerformed

    private void PvCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PvCActionPerformed
        // TODO add your handling code here:
        P1Name.setVisible(true);
    }//GEN-LAST:event_PvCActionPerformed

    private void P1NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1NameMouseClicked
        // TODO add your handling code here:
        P1Name.setText(null);
        P1Name.enable(true);
    }//GEN-LAST:event_P1NameMouseClicked

    private void P2NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P2NameMouseClicked
        // TODO add your handling code here:
        P2Name.setText(null);
        P2Name.enable(true);
    }//GEN-LAST:event_P2NameMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        MainSound.stop();
        p1name=P1Name.getText();
        System.out.println(p1name);
        this.setVisible(false);
        //new Frame1().setVisible(true);
        Frame1 f=new Frame1();
        f.avatar(j);
        f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void P1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1NameActionPerformed

    private void P2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P2NameActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        // TODO add your handling code here:
        //jLabel2.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel2MouseWheelMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel2MouseWheelMoved

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void PvCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PvCMouseEntered
        // TODO add your handling code here:
        jLabel2.setVisible(true);
    }//GEN-LAST:event_PvCMouseEntered

    private void PvCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PvCMouseExited
        // TODO add your handling code here:
        jLabel2.setVisible(false);
    }//GEN-LAST:event_PvCMouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel3MouseExited

    private void PvPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PvPMouseEntered
        // TODO add your handling code here:
        jLabel3.setVisible(true);
    }//GEN-LAST:event_PvPMouseEntered

    private void PvPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PvPMouseExited
        // TODO add your handling code here:
        jLabel3.setVisible(false);
    }//GEN-LAST:event_PvPMouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        
        
        
        if(i==0){
        
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/joker.png"))); 
            j="joker";
        
        }
        
        else if(i==1){
            
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diablo.png")));
            j="diablo";
        }
        else if(i==2){
        
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deadShot.png")));
            j="dead";
        
        }
        else if(i==3){
        
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/military.png")));
            
            j="mili";
            
            i=-1;
        
        }
        
        i++;
        
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField P1Name;
    private javax.swing.JTextField P2Name;
    private javax.swing.JButton PvC;
    private javax.swing.JButton PvP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
